# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tweets and feelings' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tweets and feelings
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod "ImageSlideshow/Alamofire"
  # pod 'NVActivityIndicatorView', '~> 4.4.0'
  pod 'Toast-Swift', '~> 3.0.1'
  pod 'expanding-collection'

  target 'Tweets and feelingsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tweets and feelingsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
